import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from 'next/headers'
import { verifySession, COOKIE_NAME } from '@/lib/auth'
import LogoutButton from '@/components/LogoutButton'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const token = cookieStore.get(COOKIE_NAME)?.value
  const session = token ? verifySession(token) : null
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="site-header">
          <div className="container flex items-center justify-between py-3">
            <div className="brand text-lg">BeeApp</div>
            <nav className="site-nav flex items-center gap-5 text-sm">
              {!session && <a href="/">Login</a>}
              <a href="/dashboard">Dashboard</a>
              {session && <span aria-hidden className="opacity-40">•</span>}
              {session && <LogoutButton />}
            </nav>
          </div>
        </header>
        <main>
          {children}
        </main>
        <footer className="container py-8 muted text-sm">
          © {new Date().getFullYear()} BeeApp
        </footer>
      </body>
    </html>
  );
}
